In [89]:
import dlib
import tkinter as tk
from tkinter import filedialog as fd
import cv2 as cv
import numpy as np
from PIL import Image, ImageTk
import os
import openpyxl
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg


In [90]:
def sub_show_image(root,image_list,image_list_numpy,canvas):
    def draw_bar_chart(canvas3, data_values, x, y):
        canvas5 = canvas.getCanvas5()
        canvas5.delete('all')
        # Tạo một hình vẽ của Matplotlib
        fig = Figure(figsize=(4, 2), dpi=100)
        ax = fig.add_subplot(111)
        # Vẽ biểu đồ cột
        ax.bar(range(len(data_values)), data_values, align='center')
        canvas5.create_text(70,20,text="Predict: "+image_label[np.argmax(data_values)],font=("Arial", 12))
        # Tạo một widget Canvas để chứa biểu đồ Matplotlib
        canvas3 = FigureCanvasTkAgg(fig, master=canvas3)
        canvas_widget = canvas3.get_tk_widget()
        # Sử dụng phương thức .place() để đặt vị trí của biểu đồ
        canvas_widget.place(x=x, y=y)
        
    def show_image(image_index):
        # Hiển thị ảnh tương ứng với chỉ số image_index
        canvas4.itemconfig(image_item, image=image_list[image_index])
        # Cập nhật chỉ số hiện tại
        current_image_index.set(image_index)
        predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
        draw_bar_chart(canvas3,predict[0],20,400)

    def next_image():
        # Chuyển đến ảnh tiếp theo
        current_index = current_image_index.get()
        next_index = (current_index + 1) % len(image_list)
        show_image(next_index)
    if(len(image_list)!=0):
        canvas3 = canvas.getCanvas3()
        canvas4 = canvas.getCanvas4()
        model = load_model("Model\\my_model0.keras")
        # Tạo một mảng hiển thị ảnh
        current_image_index = tk.IntVar()
        current_image_index.set(0)
        image_item = canvas4.create_image(0, 0, anchor=tk.NW, image=image_list[0])
        
        show_image(0)
        # Tạo nút để chuyển ảnh
        next_button = tk.Button(root, text="Next Image", command=next_image)
        next_button.place(x=890,y=170)


In [91]:
class Canvas():
    def __init__1(self):
        self.canvas1 = tk.Canvas(self.window, width=700, height=695, bg='white')
        self.canvas1.create_rectangle(2, 3, 695, 695, outline='black', width=2)
        self.canvas1.create_text(300,25,text="NHẬN DIỆN KHUÔN MẶT",font=("Arial", 25))
        self.canvas1.create_line(5, 50, 695, 50, fill="black", width=2)
        self.canvas1.place(x=0,y=0)
    def __init__2(self):
        self.canvas2 = tk.Canvas(self.window, width=340, height=700, bg='white')
        self.canvas2.create_rectangle(5,3,330,695,outline='black',width=2)
        self.canvas2.place(x=700,y=0)
        self.canvas2.create_text(150,15,text="List",font=("Arial", 12))
    def __init__4(self):
        self.canvas4 = tk.Canvas(self.window, width=150, height=150, bg='white')
        self.canvas4.place(x=860,y=5)

    def __init__3(self):
        self.canvas3 = tk.Canvas(self.window, width=475, height=695, bg='white')
        self.canvas3.create_rectangle(5,3,475,695,outline='black',width=2)
        self.canvas3.create_line(7, 400, 475, 400, fill="black", width=2)
        self.canvas3.place(x=700,y=0)
    def __init__5(self):
        self.canvas5 = tk.Canvas(self.window, width=200, height=30, bg='white')
        self.canvas5.place(x=830,y=250)
    def __init__(self,window):
        self.window = window
        self.__init__1()
        # self.__init__2()
        self.__init__3()
        self.__init__4()
        self.__init__5()
    def init(self):
        self.__init__(self.window)
    def clear_console(self):
        self.canvas1.delete('all')
        # self.canvas2.delete('all')
        self.canvas3.delete('all')
        self.canvas4.delete('all')
        self.canvas5.delete('all')
        self.init()
    def getCanvas1(self):
        return self.canvas1
    def getCanvas2(self):
        return self.canvas2
    def getCanvas4(self):
        return self.canvas4
    def getCanvas3(self):
        return self.canvas3
    def getCanvas5(self):
        return self.canvas5

In [92]:
def chooseModel():
    name = fd.askopenfilename(filetypes=[("Keras Files", "*.keras")])
    model_name[0] = name

In [93]:
class GUI():
    def __init__(self):
        self.window = tk.Tk()
        # setting attribute
        # self.window.attributes('-fullscreen', True)
        self.window.geometry("2000x800")
        self.window.title("Nhận diện người")
        self.window.configure(bg='lightblue')
        my_label = tk.Label(self.window, text="Nút bấm")
        my_label.config(fg='black')
        my_label.config(bg='lightblue')
        my_label.config(font=('Times New Roman', 15))
        my_label.place(x=1320,y=10)
        self.canvas= Canvas(self.window)

        self.entry = tk.Entry(self.window)
        self.entry.place(x=1300,y=80)
    
        self.button0 = tk.Button(self.window,text= "Train mô hình",command= lambda: train())
        self.button0.place(x=1330,y=200)
        
        self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
        self.button1.place(x=300,y=705)

        self.button2 = tk.Button(self.window,text="   Chụp hình   ",command=lambda:button2_clicked(self.window,self.entry,self.canvas))
        self.button2.place(x=1330,y=110)

        self.button2 = tk.Button(self.window,text="   Chon mô hình   ",command=chooseModel)
        self.button2.place(x=1320,y=350)

        self.button3 = tk.Button(self.window,text="    Làm mới    ",command=lambda: self.canvas.clear_console())
        self.button3.place(x=1330 ,y=500)

        self.button4 = tk.Button(self.window,text="    Đóng    ",command= lambda:self.close())
        self.button4.place(x=1335,y=680)

        # Chạy vòng lặp chính
        self.window.mainloop()
    def close(self):
        self.window.destroy()

In [94]:
def write_file(list_MSSV,file_path):

    # Đọc dữ liệu từ file Excel
    workbook = openpyxl.load_workbook(file_path)
    sheet = workbook.active

    data = []
    print(list_MSSV)
    for row in sheet.iter_rows(min_row=3, values_only=True):
        # print(row,end="\n")
        stt, MSSV, Ho, Ten, Lop, diem_danh,*empty_value = row
        # print(Ten)
        if MSSV in list_MSSV:
            diem_danh+=1
        data.append({"stt": stt, "Mã sinh viên": MSSV, "Họ": Ho, "Tên": Ten, "Lớp":Lop, "Điểm danh": diem_danh})
    # Tạo một workbook mới
    workbook = openpyxl.Workbook()
    sheet = workbook.active

    # Ghi tiêu đề cột
    sheet.append(["TT", "MSSV", "Họ", "tên sinh viên","Lớp","Điểm danh" ])

    # Ghi dữ liệu vào sheet
    for entry in data:
        sheet.append([entry["stt"], entry["Mã sinh viên"], entry["Họ"], entry["Tên"], entry["Lớp"],entry["Điểm danh"]])

    # Lưu workbook thành file Excel mới
    workbook.save(file_path)


In [95]:
class train():
    def __init__(self):
        self.base_folder = "./Dataset1/"
        # Khởi tạo danh sách để lưu trữ hình ảnh và nhãn (labels)
        self.images = []
        self.labels = []
        # Khởi tạo một từ điển để ánh xạ từ tên nhãn (string) sang số nguyên
        self.label_to_int = {}
        self.int_to_label = {}
        self.current_label = 0
        self.create_data()
        self.model()
    def create_data(self):
        # Duyệt qua tất cả các thư mục con trong thư mục chính
        for person_folder in os.listdir(self.base_folder):
            person_path = os.path.join(self.base_folder, person_folder) 
            # Kiểm tra nếu person_path là một thư mục
            if os.path.isdir(person_path):
                # Lặp qua tất cả các tệp trong thư mục của người đó
                for filename in os.listdir(person_path):
                    # Kiểm tra nếu tệp có định dạng hình ảnh (vd: jpg, jpeg, png)
                    if filename.endswith((".jpg", ".jpeg", ".png")):
                        # Tạo đường dẫn đầy đủ đến tệp
                        image_path = os.path.join(person_path, filename)
                        # Đọc hình ảnh bằng OpenCV
                        image = cv.imread(image_path)

                        if np.random.rand() > 0.9:
                            image = cv.flip(image, 1)
                        # Chuyển hình ảnh thành ma trận và thêm vào danh sách images

                        image = cv.cvtColor(image,cv.COLOR_BGR2GRAY)
                        # image = cv.resize(image, (128, 128))
                        image = cv.resize(image, (40, 40))
                        self.images.append(image)
                        
                        # Kiểm tra xem nhãn này đã được thêm vào từ điển chưa
                        if person_folder not in self.label_to_int:
                            self.label_to_int[person_folder] = self.current_label
                            self.int_to_label[self.current_label] = person_folder
                            self.current_label += 1
                        # Chuyển đổi tên nhãn từ chuỗi sang số nguyên và thêm vào danh sách labels
                        label = self.label_to_int[person_folder]
                        self.labels.append(label)

        # Chuyển danh sách images và labels thành các mảng NumPy
        images_array = np.array(self.images)
        labels_array = np.array(self.labels)

        # Chuẩn hóa giá trị pixel để nằm trong khoảng [0, 1]
        images_array = images_array / 255.0
        self.train_images = images_array
        self.train_labels = labels_array
    def model(self):
        model = models.Sequential()
        model.add(layers.Flatten(input_shape=(40, 40,1))) 
        model.add(layers.Dense(128, activation='relu'))
        # model.add(layers.Dense(64, activation='relu'))
        model.add(layers.Dropout(0.5))
        model.add(layers.Dense(self.current_label,activation='softmax'))
        model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
        model.fit(self.train_images, self.train_labels, epochs=20)  # Tăng số epoch để huấn luyện lâu hơn
        all_name = [f for f in os.listdir('Model')] 
        max = 1
        for i in all_name:
            num =int( i.split('.')[0][-1])
            if (num>max): max= num
        model.save("Model/my_model"+str(max+1) +"."+"keras")

In [96]:
class add_person():
    def __init__(self,window=None,canvas=None,name=None):
        # if window==None:return
        self.cam = cv.VideoCapture(0)
        self.canvas= canvas.getCanvas1()
        self.clear = canvas.clear_console
        self.name=name
        self.list_image=[]
        self.face = cv.CascadeClassifier("haarcascade_frontalface_default.xml")
        self.stop=0
        self.captured_button = tk.Button(window,text="Stop",command=lambda: self.stop_fuc())
        self.captured_button.place(x=1350,y=540)
        self.numberOfImage = 0
        self.numberOfLoop = 0
    def stop_fuc(self):self.stop=1
    def capture(self): 
        check,frame = self.cam.read()
        frame = cv.resize(frame,(1183, 733))
        if check:
            faces = self.face.detectMultiScale(frame,scaleFactor=1.25,minNeighbors=5)
            for (x,y,w,h) in faces:
                cut_face = frame[y:y+h, x:x+w]
                cut_face = cv.resize(cut_face,(128,128))
                if self.numberOfLoop %15==0:
                    self.numberOfImage+=1
                    self.list_image.append(cut_face)
                cv.putText(frame,self.name, (x, y-10), cv.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
                cv.rectangle(frame,(x, y), (x+w, y+h), (0, 255, 0), 2)
            self.image = cv.cvtColor(frame, cv.COLOR_BGR2RGB) # to RGB
            self.image = Image.fromarray(self.image) # to PIL format
            self.image = ImageTk.PhotoImage(image=self.image) # to ImageTk format
            # Update image
            self.canvas.create_image(4,55,anchor = tk.NW, image= self.image)
            self.canvas.img_tk= self.image
            #check i to return
            if(self.stop or self.numberOfImage>=700):
                self.cam.release()
                self.clear()
                self.captured_button.destroy()
                self.Train(self.name,self.list_image)
                return
            # Repeat every 'interval' ms
            self.canvas.after(50,self.capture)
    def Train(self,name,list_image):
        all_name_path = [os.path.join("DataSet1",f) for f in os.listdir("DataSet1")]
        all_name = [x.split('\\')[-1] for x in all_name_path]
        if name not in all_name:
            os.mkdir("DataSet1\\" + name)
        max = 0
        for x in os.listdir("DataSet1\\"+name):
            x=x.split("(")[-1].split(")")[0]
            if int(x)>max:max = int(x)
        max +=1
        for image in list_image:
            cv.imwrite("DataSet1\\"+name + "\\"+name+"("+str(max)+")"+".jpg",image)
            max+=1
        train()
    def pick_picture(self):
        image_path = fd.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg")])
        image = cv.imread(image_path)
        self.save_image(image_path.split('/')[-1].split('.')[0],image)
        

In [97]:
def button2_clicked(window,entry,canvas):
    canvas.clear_console()
    name=entry.get()
    if name == "":return
    a = add_person(window,canvas,name)
    a.capture()


In [98]:
class show_image():
    def __init__(self,window,canvas):
        self.canvas = canvas
        self.window =window
        self.attendance=[]
        self.detect_face = cv.CascadeClassifier("haarcascade_frontalface_default.xml")
    def load_data(self):
        if model_name[0] =='':
            self.model = load_model("Model\\my_model0.keras")
        else: self.model = load_model(model_name[0])
        self.all_name = [name for name in os.listdir("DataSet1")]
        print(self.all_name)
        path = fd.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg")])
        if path == '': 
            return 0
        self.image = cv.imread(path)
    def show_image(self):
        image_list = []
        image_list_numpy = []
        check =False
        if self.load_data() == 0: return

        gray_image = cv.cvtColor(self.image,cv.COLOR_BGR2GRAY)
        faces = self.detect_face.detectMultiScale(gray_image,scaleFactor=1.15,minNeighbors=5)
        for (x,y,w,h) in faces:
                cut_face = gray_image[y:y+h, x:x+w]
                cut_face = cv.resize(cut_face,(40,40))
                image_list_numpy.append(cut_face)
                # Chuyển đổi thành đối tượng Image của Pillow
                pil_image = Image.fromarray(cv.resize(cut_face,(150,150)))
                # Chuyển đổi thành đối tượng ImageTk.PhotoImage
                photo_image = ImageTk.PhotoImage(pil_image)
                # Thêm vào image_list
                image_list.append(photo_image)
                predict = self.model.predict(np.expand_dims(cut_face,axis=0))
                index = np.argmax(predict)
                print(predict)
                name = self.all_name[index]
                cv.putText(self.image,name, (x, y-10), cv.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
                cv.rectangle(self.image,(x, y), (x+w, y+h), (0, 255, 0), 2)
                check = True
        img = Image.fromarray(cv.cvtColor(self.image,cv.COLOR_BGR2RGB))
        img = img.resize((680, 635), Image.LANCZOS)
        img=ImageTk.PhotoImage(img)
        panel = tk.Label(self.window, image=img)
        panel.image = img
        panel.place(x=4,y=55)
        cv.destroyAllWindows()
        sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
        

In [99]:
if __name__== '__main__':
    image_label = [name for name in os.listdir("DataSet1")]
    model_name = ['']
    GUI()
    

Epoch 1/20
169/169 [==============================] - 1s 5ms/step - loss: 1.2986 - accuracy: 0.5407
Epoch 2/20
169/169 [==============================] - 1s 5ms/step - loss: 0.7155 - accuracy: 0.7619
Epoch 3/20
169/169 [==============================] - 1s 5ms/step - loss: 0.5478 - accuracy: 0.8170
Epoch 4/20
169/169 [==============================] - 1s 5ms/step - loss: 0.4671 - accuracy: 0.8369
Epoch 5/20
169/169 [==============================] - 1s 5ms/step - loss: 0.4176 - accuracy: 0.8528
Epoch 6/20
169/169 [==============================] - 1s 5ms/step - loss: 0.3833 - accuracy: 0.8648
Epoch 7/20
169/169 [==============================] - 1s 5ms/step - loss: 0.3485 - accuracy: 0.8843
Epoch 8/20
169/169 [==============================] - 1s 5ms/step - loss: 0.3502 - accuracy: 0.8804
Epoch 9/20
169/169 [==============================] - 1s 6ms/step - loss: 0.3181 - accuracy: 0.8846
Epoch 10/20
169/169 [==============================] - 1s 5ms/step - loss: 0.3000 - accuracy: 0.8969

Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 35, in show_image
    predict = self.model.predict(np.expand_dims(cut_face,axis=0))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\app\Python\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hnguy\AppData\Local\Temp\__autograph_generated_fileg973yrjq.py", line 1

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 63ms/step
[[1. 0. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 46ms/step
[[0.03429193 0.         0.         0.         0.         0.9657081
  0.        ]]
1/1 [==============================] - 0s 27ms/step
[[3.8478894e-11 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00 0.0000000e+00]]
1/1 [==============================] - 0s 26ms/step
[[0. 0. 1. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 41ms/step
[[0. 1. 0. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 33ms/step
[[0. 0. 0. 0. 0. 1. 0.]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 63ms/step
[[0. 0. 1. 0. 0. 0. 0.]]
1/1 [==============================] - 0s 35ms/step
[[0. 0. 0. 1. 0. 0. 0.]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 63ms/step
[[0. 0. 0. 1. 0. 0. 0.]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 61ms/step
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 6.4389846e-20
  0.0000000e+00 0.0000000e+00]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 60ms/step
[[0. 0. 1. 0. 0. 0. 0.]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     

['N21DCCN017', 'N21DCCN032', 'N21DCCN067', 'N21DCCN069', 'N21DCCN075', 'N21DCCN076', 'N21DCCN092']
1/1 [==============================] - 0s 53ms/step
[[0. 0. 0. 0. 1. 0. 0.]]
1/1 [==============================] - 0s 51ms/step
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  7.0484205e-32 0.0000000e+00]]


Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\app\Python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\3560458192.py", line 22, in <lambda>
    self.button1 = tk.Button(self.window, text="Chọn ảnh",command=lambda:show_image(self.window,self.canvas).show_image())
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\1851038500.py", line 49, in show_image
    sub_show_image(self.window,image_list,image_list_numpy,self.canvas)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 39, in sub_show_image
    show_image(0)
  File "C:\Users\hnguy\AppData\Local\Temp\ipykernel_5936\2678604157.py", line 22, in show_image
    predict = model.predict(np.expand_dims(image_list_numpy[image_index],axis=0))
     